name: Build

on:
  push:
    branches: [ main, development]
  pull_request:
    branches: [ main, development]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Check if CLI works
        run: node dist/index.js --version
